Add files via upload
sheilacls/DvNube-Bootcamp-Exercicios pull request #1
Opened 2023-02-15 18:01 UTC by sheilacls

2023-02-16 01:29 UTC, dvnube requested changes
pedir ajuda pra turma pra corrigir seu algoritmo
caso não consiga ajuda, me avisar

2023-02-16 16:41 UTC, dvnube requested changes

2023-02-16 16:41 UTC, dvnube commented on Algoritmoescovarosdentes.txt
> +Se
```
se (sentado no sofá) então
    levantar do sofá
fimse

2023-02-16 16:41 UTC, dvnube commented on Algoritmoescovarosdentes.txt
> +Se
```
caminhar até o banheiro
se (porta fechada) então
    abrir porta
fimse
entrar no banheiro

2023-02-16 16:41 UTC, dvnube commented on Algoritmoescovarosdentes.txt
> +
```
se (escova de dente no armário) então
    abrir armário
    pegar escova
senão
    procurar escova
    se (encontrar escova então)
        pegar escova
    senão
        ligar pro mercado pra pedir escova
    fimse
fimse

se (pasta de dente no armário) então
    pegar pasta
fimse

colocar

2023-02-19 11:40 UTC, merged

2023-02-19 11:42 UTC, sheilacls commented on Algoritmoescovarosdentes.txt
> +
Inicio
Se (sentado no sofá) então
	Levantar do sofá
FimSe
Se (porta fechada) então
	Abrir a porta
FimSe
	Entrar no banheiro

Se (escova de dente no armário) então
	Abrir armário
	Pegar a escova de dentes
senão
	procurar escova
	Se (encontrar escova então)
	    pegar escova
	senão
            Ligar para o mercado
	FimSe	
FimSe

Se (pasta de dente no armário) então
	Pegar pasta
FimSe
	Escovar os dentes
Se (torneira aberta) então
	Enxaguar a boca
	senão
	abrir torneira
FimSe
Se (lavar a escova de dentes) então
	Guardar escova de dentes no armário
	Guardar a pasta de dentes no armário
FimSe
	Fechar a torneira
Se (luz acesa)
	    Apagar a luz
	    Feche a porta do banheiro
FimSe
Se (sair do banheiro) então
	    Caminhar até o sofá
	    Sentar-se novamente
FimSe
Fimalgoritmo